config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  
  root :to => 'homes#top'
  get '/home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
  end
      
  
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy] 
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
     @book = Book.find(params[:book_id])
     @favorite = current_user.favorites.new(book_id: @book.id)
     @favorite.save
     # 非同期通信化の為コメントアウト↓
      # redirect_back(fallback_location:root_path)#直前のページへとリダイレクトさせる
    end
    
    def destroy
     @book = Book.find(params[:book_id])
     @favorite = current_user.favorites.find_by(book_id: @book.id)
     @favorite.destroy
     # 非同期通信化の為コメントアウト↓
     # redirect_back(fallback_location:root_path)#直前のページへとリダイレクトさせる
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
<!--remote:trueでjsに操作を飛ばす-->
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart-pink",remote: true %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart heart_blue",remote: true %>
<% end %>

<!--render後、下の記述だとカウントとアイコンの位置がなぜかずれてしまう問題が発生-->
<!--link_toの列に、アイコンとカウントを統合。ハートの色はfavorites.scssで指定-->
 <!--%= link_to book_favorites_path(book), method: :post do %>-->
 <!--<i class="fa fa-heart" aria-hidden="true" style="color: blue;"></i>-->
 <!--%= book.favorites.count %>-->

app/views/favorites/create.js.erb
<!--'favorite-btnに対して部分テンプレートを適用する-->
$('#favorite-btn-<%= @book.id %>').html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
 <!--'favorite-btnに対して部分テンプレートを適用する-->
  $("#favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");