config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  
  root :to => 'homes#top'
  get '/home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
  end
      
  
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy] 
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,  dependent: :destroy 
  attachment :profile_image, destroy: false
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # foreign_key: "followed_id"でどのカラムを参照して欲しいのかを定義
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能。上と見た目を合わせるためにあえて記載
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
  
  # ユーザーをフォローする
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す/フォロワーがフォローした時に出来たidを探してきてdestroy
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

 # フォローしていればtrueを返す
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(searches, words)
    if searches == "perfect_match"#完全一致
       @user = User.where("name Like ?","#{words}")
    elsif searches == "forward_match"#前方一致
       @user = User.where("name Like ?","#{words}%")
    elsif searches == "backward_match"#後方一致
       @user = User.where("name Like ?","%#{words}")
    elsif searches == "partial_match"#部分一致#部分一致
       @user = User.where("name Like ?","%#{words}%")
    end
  end


  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size:"50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
         <td>フォロワー数: <%= user.followers.count %></td>
         <td>
           <!--表示されている各記事のユーザーとカレントユーザーが違う場合のみ、フォローする/しないを表示する-->
          <% if user.id != current_user.id %>
           　<% if current_user.following?(user) %>
             　<%= link_to "フォローしない", user_relationships_path(user.id), method: :delete %>
           　<% else %>
             　<%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
           　<% end %>
          <% end %>
         </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, size: "100x100", fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to  user_followings_path(user.id) do %>
	      <%=user.followings.count %>
	    <% end %>
	  </th>
	  
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to  user_followers_path(user.id) do %>
	      <%= user.followers.count %></th>
	    <% end %>
  </tr>
  
</table>
<!--変更前の@book.user.id ==current_user.idだと左側の比べたいidが都度変わってしまう可能性がある-->
<!--その時にuser_info表示されているユーザーとカレントユーザーが一緒であるかどうか？？を比べたいので-->
<!--user.id == current_user.idとなる-->
<% if user.id == current_user.id %>
　<div class='row'>
  　<%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
　</div>
<% else %>
  <div>
   <%= render 'relationships/follow_button', user: user%>
  </div><br>
<% end %>　

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
     <h2>User info</h2>
     <%= render 'info', user: current_user %>
     
     
     <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
   <h2>Users</h2>
   <%= render 'index',users: @users %> 
   </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>