config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  
  root :to => 'homes#top'
  get '/home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
  end
      
  
  
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy] 
  end

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user,optional: true
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
    
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
	def favorited_by?(user)#いいね機能のviewで使う
	    favorites.where(user_id: user.id).exists?
	end
    
     # searchとwordの引数を受けとる
  def self.looks(searches, words)
    if searches == "perfect_match"#完全一致
       @book = Book.where("title Like ?","#{words}")#("カラム名 Like ?")
    elsif searches == "forward_match"#前方一致
       @book = Book.where("title Like ?","#{words}%")
    elsif searches == "backward_match"#後方一致
       @book = Book.where("title Like ?","%#{words}")
    elsif searches == "partial_match"#部分一致#部分一致
       @book = Book.where("title Like ?","%#{words}%")
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, size:"50x50", fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<!--destroyボタンはコメントした本人の時だけ表示-->
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id),data: { confirm: '本当に消しますか？' }, class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[@book,@book_comment], local: true do |f| %>
  <%= f.text_area :comment, class: 'form-control' ,placeholder: "コメントをここに" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :Title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :Opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, size:"50x50", fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!--いいね機能↓-->
        <!--非同期通信で使用するためid入りのclass名を追加、-->
        <td id='favorite-btn-<%= book.id %>'>
        <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>
          コメント数：<%= book.book_comments.count %>
        </td>
      </tr>  
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %><!--フラッシュメッセージ表示-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      　<%= render 'users/info',user:@user %>
      <h2 class="mt-3">New book</h2>
      　<%= render 'form', book: @book_new %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		 <table class='table'>
  		   <tr>
  		    　<td>
  		       <%= link_to user_path(@book.user) do %>
             <%= attachment_image_tag(@book.user, :profile_image, size:"50x50", fallback: "no-image-icon.jpg") %><br>
             <%= @book.user.name %>
             <% end %>
          　</td>
          　<td>
             <%= link_to @book.title, book_path(@book) %>
          　</td>
          　<td>
          　  <%= @book.body %>
          　</td>
          　
          　<td id='favorite-btn-<%= @book.id %>'><!--いいね機能-->
             　<%= render 'favorites/favorite-btn',book: @book %>
            </td>
            <td><!--コメント数カウント-->
              コメント数：<%= @book.book_comments.count %>
            </td>
            <!--編集/投稿削除-->
            <% if @book.user_id == current_user.id %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
            </td>
            <td>
              <%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
            </td>
        　　<% end %>
        </tr>
      </table>
      <div id="comment_index_<%= @book.id %>">
        <!--変更前↓コメント用のフォームとコメントのリストを分けたのに@book_commentの変数をそのままにしていた-->
        <!--book_comments/indexの中では、@book_comment-->
        <!--%= render 'book_comments/index', book: @book,book_comment: @book_comment %>-->
      <%= render 'book_comments/index', book: @book %>
      </div>
      <div id="new-comments_<%= @book.id%>">
      <%= render 'book_comments/new-comments', book: @book,book_comment: @book_comment %>
      </div>
     </div>
  </div>
</div>